users:
  tj:
    name: tj
    age: 23
    email: 'tj@vision-media.ca'
  bob:
    name: 'bob'
    age: 27
  ted: { name: ted, age: 32, email: ted@tedtalks.com }
country:
  name: Österreich
  website: http://en.wikipedia.org/wiki/Austria
space:
  description: space, the final frontier
  
title: Some Title
falseme: I can see this
what: no
say: yes
trueme: found
hope: to see this

date0: 2011-05-21
date1: 2011-5-21
date2: 2011-1-2
date3: 2011-02-21 17:56
date4: 2011-04-21 5:35
date5: 2011-06-02 20:45:30

dev:
  mongo_uri: 'mongodb://localhost/calling_development'
  #errorHandling: true
  urlPrefix:''
  authentication: true
  middle: ['resmin','hmiddle']
  responsible: 'ademir.escribano@gmail.com'
  guarsdian: 'ademir.escribano@gmail.com'
